### ISSUE TITLE
we should taxit reroot the reference package

### ISSUE THREAD

**Issue by matsen** [fhcrc/microbiome-demo#1]
This sounds trivial, but we also have to re-run the various samples on the re-rooted package. Another option would just be to run everything on the new refset.

**Comment by matsen** [comment]
We can't release the new refset, so we should just reroot this one.

I just tried taxit reroot, but it failed. If it's too much work to reroot this ref pkg, then we can just wait until the next one gets released.

Also, it appears to be time to merge this dev into master, corresponding to the current master branch (`rppr`, etc)

**Comment by habnabit** [comment]
Closed by b30caa8ba7a872789accb707a0b6f4a92f073d4b.

(dev has already been merged into master.)
