### ISSUE TITLE
shocco is taking commands out of alignment

### ISSUE THREAD

**Issue by matsen** [fhcrc/microbiome-demo#3]
At least for me, the page at

http://fhcrc.github.com/microbiome-demo/

does not have the command description lining up with the command-- it's
one click off.

I had this problem before when building on a linux machine, but it
worked fine on a mac. Is the current build being done on a mac?

**Comment by metasoarous** [comment]
Yeah, I noticed that too.

**Comment by habnabit** [comment]
I think this is just something that the latest version of shocco does so that you can have a preamble. Yes, it's still being built on a mac IIRC.
